DROP TABLE IF EXISTS `GRADE_A_B`;
DROP TABLE IF EXISTS `GRADE_A`;
DROP TABLE IF EXISTS `GRADE_B`;

CREATE TABLE `GRADE_A` (
 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 `CODE` VARCHAR(100) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
   
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


CREATE TABLE `GRADE_B` (
 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 `CODE` VARCHAR(100) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
   
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


CREATE TABLE `GRADE_A_B` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CODE_A` VARCHAR(100) NOT NULL,
  `CODE_B` VARCHAR(100) NOT NULL,
  `ID_A` BIGINT UNSIGNED NOT NULL,
  `ID_B` BIGINT UNSIGNED NOT NULL,
   PRIMARY KEY (`id`),
   #FOREIGN KEY (CODE_A) REFERENCES GRADE_A(CODE) ON DELETE CASCADE ON UPDATE CASCADE, 
   #FOREIGN KEY (CODE_B) REFERENCES GRADE_B(CODE) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY (ID_A) REFERENCES GRADE_A(ID) ON DELETE CASCADE ON UPDATE CASCADE, 
   FOREIGN KEY (ID_B) REFERENCES GRADE_B(ID) ON DELETE CASCADE ON UPDATE CASCADE     
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
