DROP DATABASE IF EXISTS SPLUNK;
CREATE DATABASE IF NOT EXISTS SPLUNK;

CREATE TABLE IF NOT EXISTS SPLUNK.INVOICE (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	TRANSACTION_ID BIGINT,
	BALANCE DOUBLE,
	COMMENT VARCHAR(255),
	DATE TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SPLUNK.INVOICE_NUMBER (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	TRANSACTION_ID BIGINT,
	VERSION BIGINT,
	BALANCE DOUBLE,
	COMMENT VARCHAR(255),
	DATE TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SPLUNK.INVOICE_DATE (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	TRANSACTION_ID BIGINT,
	VERSION TIMESTAMP,
	BALANCE DOUBLE,
	COMMENT VARCHAR(255),
	DATE TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SPLUNK.EMPLOYEE (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SPLUNK.DEPARTMENT (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SPLUNK.COUNTRY (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SPLUNK.EDC (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_COUNTRY BIGINT NOT NULL,
	ID_DEPARTMENT BIGINT NOT NULL,
	ID_EMPLOYEE BIGINT NOT NULL,
	CONSTRAINT FK_ID_COUNTRY FOREIGN KEY (ID_COUNTRY) REFERENCES SPLUNK.COUNTRY (ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_ID_DEPARTMENT FOREIGN KEY (ID_DEPARTMENT) REFERENCES SPLUNK.DEPARTMENT (ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_ID_EMPLOYEE FOREIGN KEY (ID_EMPLOYEE) REFERENCES SPLUNK.EMPLOYEE (ID) ON DELETE CASCADE ON UPDATE CASCADE 
)ENGINE=InnoDB;

COMMIT;

